#!/usr/bin/env python3
"""Independent-oracle + differential + fault-sensitivity checks.

The expected/*.txt files are deliberately hand-authored observations. They are not
regenerated by either implementation. This gives the experiment a tiny independent
oracle instead of treating Lean/Rust agreement as correctness.
"""
import difflib
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEAN = ROOT / ".lake" / "build" / "bin" / "stage_minus_one"
RUST = ROOT / "rust" / "target" / "debug" / "stage-minus-one-rust"
EXPECTED = ROOT / "expected"
FIXTURES = ["nested", "inherit"]
FAULTS = ["drop_text", "off_by_one_width", "wrong_sibling_y", "wrong_paint_order"]
GENERATED_CASES = 128


def run(cmd, env=None):
    return subprocess.check_output([str(x) for x in cmd], text=True, env=env).strip()


def expected(fixture):
    return (EXPECTED / f"{fixture}.txt").read_text().strip()


def diff(label, want, got):
    body = "\n".join(difflib.unified_diff(
        want.splitlines(), got.splitlines(), fromfile=f"expected/{label}", tofile=label, lineterm=""
    ))
    return body or f"{label}: mismatch"


def lean_generated(i):
    return run([LEAN, "gen", str(i)])


def rust_generated(i):
    return run([RUST, "gen", str(i)])


def rust(fixture, fault=None):
    env = os.environ.copy()
    if fault:
        env["STAGE_MINUS_ONE_FAULT"] = fault
    return run([RUST, fixture], env=env)


def main():
    bad = []

    # Independent observations: both implementations must separately match them.
    for fixture in FIXTURES:
        want = expected(fixture)
        lean_out = run([LEAN, fixture])
        rust_out = rust(fixture)
        if lean_out != want:
            bad.append(diff(f"{fixture}:lean", want, lean_out))
        if rust_out != want:
            bad.append(diff(f"{fixture}:rust", want, rust_out))
        if lean_out != rust_out:
            bad.append(diff(f"{fixture}:differential", lean_out, rust_out))

    # Broad bounded family: no independent oracle claim here; this is differential
    # refinement evidence intended to exercise many width/padding/wrapping combinations.
    for i in range(GENERATED_CASES):
        lean_out = lean_generated(i)
        rust_out = rust_generated(i)
        if lean_out != rust_out:
            bad.append(diff(f"generated-{i}:differential", lean_out, rust_out))
            break

    # Projection/harness sensitivity: every deliberate semantic corruption must be
    # observable on at least one independent fixture.
    for fault in FAULTS:
        detected = any(rust(fixture, fault) != expected(fixture) for fixture in FIXTURES)
        if not detected:
            bad.append(f"fault escaped observation: {fault}")

    if bad:
        print("FAIL")
        print("\n\n".join(bad))
        return 1

    print(
        f"PASS: {len(FIXTURES)} independent golden fixtures and {GENERATED_CASES} bounded generated cases agree; "
        f"{len(FAULTS)} deliberate faults detected"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
